FROM node:18-alpine

WORKDIR /app

# Устанавливаем зависимости для разработки
RUN apk add --no-cache libc6-compat

# Копируем только файлы package.json и package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

ENV WATCHPACK_POLLING=true
ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]
