version: '3.8'

services:
  app:
    container_name: anime
    image: docimg12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./app:/app
      - avatar_storage:/app/avatars

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - app

volumes:
  postgres_data:
  avatar_storage:
    driver: local
