version: '3.8'

services:
  app:
    container_name: anime
    image: docimg12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./uploads/avatars:/backend/uploads/avatars
      - ./uploads/banners:/backend/uploads/banners

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  avatar_storage:
  banner_storage:
