"""comments

Revision ID: 86aae79dae5a
Revises: 96512bf8a5c9
Create Date: 2025-06-07 00:48:04.959460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86aae79dae5a'
down_revision: Union[str, None] = '96512bf8a5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('id_of_anime', sa.String(), nullable=False))
    op.create_index(op.f('ix_comment_id_of_anime'), 'comment', ['id_of_anime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_id_of_anime'), table_name='comment')
    op.drop_column('comment', 'id_of_anime')
    # ### end Alembic commands ###
