"""add anime0002

Revision ID: 5ac7edbd71de
Revises: 
Create Date: 2025-01-06 02:43:34.315943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac7edbd71de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass