"""Initial migrations

Revision ID: 609e9ca570f8
Revises: 
Create Date: 2024-11-03 12:46:07.672513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609e9ca570f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('anime_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('category', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_anime_image'), 'anime', ['anime_image'], unique=False)
    op.create_index(op.f('ix_anime_category'), 'anime', ['category'], unique=False)
    op.create_index(op.f('ix_anime_description'), 'anime', ['description'], unique=False)
    op.create_index(op.f('ix_anime_rating'), 'anime', ['rating'], unique=False)
    op.create_index(op.f('ix_anime_title'), 'anime', ['title'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_description', sa.String(), nullable=True),
    sa.Column('user_avatar', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.create_index(op.f('ix_users_user_avatar'), 'users', ['user_avatar'], unique=False)
    op.create_index(op.f('ix_users_user_description'), 'users', ['user_description'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_description'), table_name='users')
    op.drop_index(op.f('ix_users_user_avatar'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_anime_title'), table_name='anime')
    op.drop_index(op.f('ix_anime_rating'), table_name='anime')
    op.drop_index(op.f('ix_anime_description'), table_name='anime')
    op.drop_index(op.f('ix_anime_category'), table_name='anime')
    op.drop_index(op.f('ix_anime_anime_image'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
