"""anime003

Revision ID: 6a7aa4bf9b69
Revises: dcd8dd2b41aa
Create Date: 2024-11-25 02:22:59.360114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a7aa4bf9b69'
down_revision: Union[str, None] = 'dcd8dd2b41aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:

    op.add_column('anime', sa.Column('category', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
