"""фікс картинок

Revision ID: b67ac3437777
Revises: 17d288c55dd4
Create Date: 2024-11-25 01:59:19.333168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67ac3437777'
down_revision: Union[str, None] = '17d288c55dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('anime_images', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_index('ix_anime_anime_image', table_name='anime')
    op.drop_column('anime', 'anime_image')
    op.drop_index('ix_users_password', table_name='users')
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.create_index('ix_users_password', 'users', ['password'], unique=True)
    op.add_column('anime', sa.Column('anime_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_anime_anime_image', 'anime', ['anime_image'], unique=False)
    op.drop_column('anime', 'anime_images')
    # ### end Alembic commands ###
