"""anime002

Revision ID: dcd8dd2b41aa
Revises: 237ab3d42087
Create Date: 2024-11-25 02:19:56.650958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcd8dd2b41aa'
down_revision: Union[str, None] = '237ab3d42087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'category',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_anime_category', table_name='anime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_anime_category', 'anime', ['category'], unique=False)
    op.alter_column('anime', 'category',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
